name: toxic_flutter
description: "Toxic Flutter additions from inspired from the toxic package"
version: 1.0.0
homepage: https://github.com/ArcaneArts/toxic_flutter
environment:
  sdk: ^3.5.0-315.0.dev
  flutter: ">=1.17.0"
dependencies:
  rxdart: any
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: